src/Entity/Business.php
<?php

namespace App\Entity;

use App\Repository\BusinessRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BusinessRepository::class)]
class Business
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'businesses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $caption = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $postcode = null;

    #[ORM\Column(length: 13, nullable: true)]
    private ?string $phone = null;

    #[ORM\ManyToOne(inversedBy: 'businesses')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Country $country = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_created = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_modify = null;

    #[ORM\OneToMany(mappedBy: 'business', targetEntity: Menu::class, orphanRemoval: true)]
    private Collection $menus;

    #[ORM\Column(length: 50)]
    private ?string $state = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $twitter_profile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $facebook_profile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $instagram_profile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $web = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imagen = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    public function __construct()
    {
        $this->menus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCaption(): ?string
    {
        return $this->caption;
    }

    public function setCaption(string $caption): self
    {
        $this->caption = $caption;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(?string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateModify(): ?\DateTimeInterface
    {
        return $this->date_modify;
    }

    public function setDateModify(?\DateTimeInterface $date_modify): self
    {
        $this->date_modify = $date_modify;

        return $this;
    }

    /**
     * @return Collection<int, Menu>
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus[] = $menu;
            $menu->setBusiness($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->menus->removeElement($menu)) {
            // set the owning side to null (unless already changed)
            if ($menu->getBusiness() === $this) {
                $menu->setBusiness(null);
            }
        }

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTwitterProfile(): ?string
    {
        return $this->twitter_profile;
    }

    public function setTwitterProfile(?string $twitter_profile): self
    {
        $this->twitter_profile = $twitter_profile;

        return $this;
    }

    public function getFacebookProfile(): ?string
    {
        return $this->facebook_profile;
    }

    public function setFacebookProfile(?string $facebook_profile): self
    {
        $this->facebook_profile = $facebook_profile;

        return $this;
    }

    public function getInstagramProfile(): ?string
    {
        return $this->instagram_profile;
    }

    public function setInstagramProfile(?string $instagram_profile): self
    {
        $this->instagram_profile = $instagram_profile;

        return $this;
    }

    public function getWeb(): ?string
    {
        return $this->web;
    }

    public function setWeb(?string $web): self
    {
        $this->web = $web;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(?string $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }
}

src/Entity/Language.php
<?php

namespace App\Entity;

use App\Repository\LanguageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LanguageRepository::class)]
class Language
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 2)]
    private ?string $principal = null;

    #[ORM\Column(length: 2, nullable: true)]
    private ?string $lang_02 = null;

    #[ORM\Column(length: 2, nullable: true)]
    private ?string $lang_03 = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrincipal(): ?string
    {
        return $this->principal;
    }

    public function setPrincipal(string $principal): self
    {
        $this->principal = $principal;

        return $this;
    }

    public function getLang02(): ?string
    {
        return $this->lang_02;
    }

    public function setLang02(?string $lang_02): self
    {
        $this->lang_02 = $lang_02;

        return $this;
    }

    public function getLang03(): ?string
    {
        return $this->lang_03;
    }

    public function setLang03(?string $lang_03): self
    {
        $this->lang_03 = $lang_03;

        return $this;
    }
}

src/Entity/Menu.php
<?php

namespace App\Entity;

use App\Repository\MenuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: MenuRepository::class)]
class Menu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'menus')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Business $business = null;

    #[ORM\OneToMany(mappedBy: 'menu', targetEntity: Dishes::class, orphanRemoval: true)]
    private Collection $dishes;

    #[ORM\Column]
    private ?bool $lang_01 = null;

    #[ORM\Column]
    private ?bool $lang_02 = null;

    #[ORM\Column]
    private ?bool $lang_03 = null;

    #[ORM\Column(length: 8)]
    private ?string $qr_code = null;

    #[ORM\Column(length: 255)]
    private ?string $caption = null;

    #[ORM\ManyToOne(inversedBy: 'menus')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Template $template = null;

    public function __construct()
    {
        $this->dishes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBusiness(): ?Business
    {
        return $this->business;
    }

    public function setBusiness(?Business $business): self
    {
        $this->business = $business;

        return $this;
    }

    /**
     * @return Collection<int, Dishes>
     */
    public function getDishes(): Collection
    {
        return $this->dishes;
    }

    public function addDish(Dishes $dish): self
    {
        if (!$this->dishes->contains($dish)) {
            $this->dishes[] = $dish;
            $dish->setMenu($this);
        }

        return $this;
    }

    public function removeDish(Dishes $dish): self
    {
        if ($this->dishes->removeElement($dish)) {
            // set the owning side to null (unless already changed)
            if ($dish->getMenu() === $this) {
                $dish->setMenu(null);
            }
        }

        return $this;
    }

    public function isLang01(): ?bool
    {
        return $this->lang_01;
    }

    public function setLang01(bool $lang_01): self
    {
        $this->lang_01 = $lang_01;

        return $this;
    }

    public function islang02(): ?bool
    {
        return $this->lang_02;
    }

    public function setlang02(bool $lang_02): self
    {
        $this->lang_02 = $lang_02;

        return $this;
    }

    public function islang03(): ?bool
    {
        return $this->lang_03;
    }

    public function setlang03(bool $lang_03): self
    {
        $this->lang_03 = $lang_03;

        return $this;
    }

    public function getQrCode(): ?string
    {
        return $this->qr_code;
    }

    public function setQrCode(string $qr_code): self
    {
        $this->qr_code = $qr_code;

        return $this;
    }

    public function getCaption(): ?string
    {
        return $this->caption;
    }

    public function setCaption(string $caption): self
    {
        $this->caption = $caption;

        return $this;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): self
    {
        $this->template = $template;

        return $this;
    }
    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Business::class, orphanRemoval: true)]
    private Collection $businesses;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $username = null;

    #[ORM\Column]
    private ?bool $isVerified = false;

    #[ORM\Column(length: 32, nullable: true)]
    private ?string $hash = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_verify = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(length: 32, nullable: true)]
    private ?string $identity_doc = null;

    #[ORM\Column(length: 12, nullable: true)]
    private ?string $phone = null;

    public function __construct()
    {
        $this->businesses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Business>
     */
    public function getBusinesses(): Collection
    {
        return $this->businesses;
    }

    public function addBusiness(Business $business): self
    {
        if (!$this->businesses->contains($business)) {
            $this->businesses[] = $business;
            $business->setUser($this);
        }

        return $this;
    }

    public function removeBusiness(Business $business): self
    {
        if ($this->businesses->removeElement($business)) {
            // set the owning side to null (unless already changed)
            if ($business->getUser() === $this) {
                $business->setUser(null);
            }
        }

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(?string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function getDateVerify(): ?\DateTimeInterface
    {
        return $this->date_verify;
    }

    public function setDateVerify(?\DateTimeInterface $date_verify): self
    {
        $this->date_verify = $date_verify;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getIdentityDoc(): ?string
    {
        return $this->identity_doc;
    }

    public function setIdentityDoc(?string $identity_doc): self
    {
        $this->identity_doc = $identity_doc;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
}

templates/control_panel/edit_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}CPanel Business{% endblock %}

{% block body %}

    {% include 'control_panel/header.html.twig' %}

    <div class="container is-fluid">
        <div class="tile is-ancestor">
            <div class="tile is-4 is-vertical is-parent">
                <div class="tile is-child box has-background-link-light">
                    <p class="title">{% trans %}Cpanel.User{% endtrans %}</p>                    
                </div>                
            </div>
            <div class="tile is-parent">
                <div class="tile is-child box has-background-link-light">
                    {{ form_start(formUser) }}
                        <div class="field">
                            <label class="label">{% trans %}Cpanel.User.Email{% endtrans %}</label>
                            <div class="control has-icons-left">            
                                {{ form_widget(formUser.email, {'attr': {'class': 'input is-success'}}) }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-utensils"></i>
                                </span>
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">{% trans %}Cpanel.User.Firstname{% endtrans %}</label>
                            <div class="control has-icons-left">            
                                {{ form_widget(formUser.firstname, {'attr': {'class': 'input is-success'}}) }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-file"></i>
                                </span>
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">{% trans %}Cpanel.User.Lastname{% endtrans %}</label>
                            <div class="control has-icons-left">            
                                {{ form_widget(formUser.lastname, {'attr': {'class': 'input is-success'}}) }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-file"></i>
                                </span>
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">{% trans %}Cpanel.User.Dni{% endtrans %}</label>
                            <div class="control has-icons-left">            
                                {{ form_widget(formUser.identityDoc, {'attr': {'class': 'input is-success'}}) }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-location-arrow"></i>
                                </span>
                            </div>
                        </div>
                        
                        <div class="field">
                            <label class="label">{% trans %}Cpanel.User.Phone{% endtrans %}</label>
                            <div class="control has-icons-left">            
                                {{ form_widget(formUser.phone, {'attr': {'class': 'input is-success'}}) }}
                                <span class="icon is-small is-left">
                                    <i class="fas fa-location-arrow"></i>
                                </span>
                            </div>
                        </div>


                        <!--Submit button-->
                        <div class="field is-grouped mt-2">
                            <div class="control">
                                <button id="submitButton" class="button is-link">{% trans %}button.caption.update{% endtrans %}</button>
                            </div>
                        </div>
                    {{ form_end(formUser) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/control_panel/header.html.twig
<section class="hero contenedor">
    <figure class="image">
        <img src="{{ asset('images/user.png')}}">
    </figure>
    <div class="hero-body texto-encima">
        <p class="title">
            {% trans %}Cpanel.Title{% endtrans %}
        </p>
        <p class="subtitle">
            {% trans %}Cpanel.Subtitle{% endtrans %}            
        </p>
    </div>
</section>
<section class="box">
    <nav class="breadcrumb has-bullet-separator is-small" aria-label="breadcrumbs">
        <ul>
            {% for migas in breadcrumb %}
                {% if migas.active == true %}
                    <li class="is-active"><a aria-current="page" href="#">{{ migas.title }}</a></li>
                {% else %}                    
                    <li><a aria-current="page" href="{{ path(migas.href, migas.parameters) }}">{{ migas.title }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
</section>

templates/control_panel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}

    {% include 'control_panel/header.html.twig' %}
    
    <div class="container is-fluid">
        <!-- tile -->
        <div class="tile is-ancestor">
            <div class="tile is-3 is-vertical is-parent">
                <div class="tile is-child box has-background-link-light">
                    {% if business %}
                        <a href="{{ path('app_edit_business', {'hash': user.hash }) }}"><span class="icon is-size-4 is-pulled-right"><i class="fa fa-edit"></i></span></a>
                    {% endif %}
                    <p class="title">{% trans %}Cpanel.Business{% endtrans %}</p>
                    {% if business %}
                        <div class="card">                            
                            <div class="card-content">
                                <div class="content">
                                        <p class="title is-4">{{ business.caption }}</p>
                                    </div>
                                <div class="media">
                                    <div class="media-left">
                                        <figure class="image is-48x48">
                                            <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        
                                        <p class="subtitle is-6">{{ business.address }}, {{ business.city }}</p>
                                    </div>
                                </div>
                                <div class="content">
                                    <p><ion-icon src="{{ asset('images/ico/call-sharp.svg') }}"></ion-icon> {{ business.phone }}</p>
                                    <p class="is-italic">{{ business.description }}</p>
                                    {% if business.twitterProfile %}
                                        {% set userTw = business.twitterProfile | split('/') %}
                                        <p class="overflow">
                                            <ion-icon name="logo-twitter"></ion-icon>
                                            <a href="{{business.twitterProfile}}">@{{ userTw[(userTw|length) - 1] }}</a>
                                        </p>
                                    {% endif %}
                                    {% if business.facebookProfile %}
                                        {% set userFc = business.facebookProfile | split('/') %}
                                        <p class="overflow">
                                            <ion-icon name="logo-facebook"></ion-icon>
                                            <a href="{{business.facebookProfile}}">{{ userFc[(userFc|length) - 1] }}</a>
                                        </p>
                                    {% endif %}
                                    {% if business.instagramProfile %}
                                        {% set userIn = business.instagramProfile | split('/') %}
                                        <p class="overflow">
                                            <ion-icon name="logo-instagram"></ion-icon>
                                            <a href="{{business.instagramProfile}}">{{ userIn[(userIn|length) - 1] }}</a>
                                        </p>
                                    {% endif %}
                                    {% if business.web %}
                                        <p class="overflow">
                                            <ion-icon src="{{ asset('images/ico/globe-outline.svg')}}"></ion-icon>
                                            <a href="{{business.web}}">{{ business.web }}</a>
                                        </p>
                                    {% endif %}                                    
                                </div>
                            </div>
                        </div>                        
                    {% else %}
                        <div class="field is-grouped">
                            <div class="control">
                                <button id="submitButton" class="button is-link" onclick="location.href='{{ path('app_add_business', {'hash': user.hash })}}'">{% trans %}Cpanel.Btn.Create{% endtrans %}</button>
                            </div>
                        </div>
                    {% endif %}
                    
                </div>
                <div class="tile is-child box has-background-danger-light">
                    <a href="{{ path('app_edit_user', {'hash': user.hash }) }}"><span class="icon is-size-4 is-pulled-right"><i class="fa fa-edit"></i></span></a>
                    <p class="title">{% trans %}Cpanel.User{% endtrans %}</p>
                    <label class="label">{% trans %}Cpanel.Email{% endtrans %}</label>                    
                    <p>{{ user.email }} <ion-icon src="{{ asset('images/ico/checkmark-done-sharp.svg')}}" class="has-text-success"></ion-icon></p>                    
                    <label class="label">{% trans %}Cpanel.Username{% endtrans %}</label>
                    <p>{{ user.firstname }} {{ user.lastname }}</p>
                </div>
            </div>
            <div class="tile is-parent">
                <div class="tile is-child box has-background-link-light">                    
                    <p class="title">{% trans %}Cpanel.Menu{% endtrans %}</p>
                    {% if menues|length == 0 %}
                        <label class="label">{% trans %}Cpanel.Menu.Create{% endtrans %}</label>                        
                        <div class="field is-grouped">
                            {% if business %}
                                <div class="control">
                                    <button id="submitButton" class="button is-link" onclick="location.href='{{ path('app_edit_menu', {'hash': user.hash }) }}'">{% trans %}Cpanel.Btn.CreateMenu{% endtrans %}</button>
                                </div>
                                {% if menu %}
                                    <img src="{{ qr_code_url('My QR Code') }}" height="75" width="75" /> TOPOTA
                                {% endif %}
                            {% else %}
                                <div class="control">
                                    <button id="submitButton" class="button is-link" disabled>{% trans %}Cpanel.Btn.CreateMenu{% endtrans %}</button>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                    <div class="tile is-ancestor">
                        {% for menu in menues %}
                            {# Al 3er elemento, crear una fila nueva #}
                            {% if loop.index == 4 %}
                                </div>
                                <div class="tile is-ancestor">
                            {% endif %}
                            <div class="tile">
                                <div class="box" style="width: 350px;">
                                    <div class="content"> 
                                        <label>{{ menu.caption }}</label>
                                        <a href="{{ path('app_edit_menu', {'hash': user.hash, 'menu_id': menu.id }) }}"><span class="icon is-size-4 is-pulled-right"><i class="fa fa-edit"></i></span></a>
                                    </div>
                                    {% set urlqr = 'https://consultalacarta.es/carta/' ~ menu.qrCode %}
                                    <div class="card">
                                        <div class="card-image">
                                            <figure class="image image is-square">
                                                <img src="{{ qr_code_url(urlqr) }}" />
                                            </figure>
                                        </div>
                                        <div class="card-content">
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="tile is-ancestor">
                        <div class="tile">
                            <div class="box" style="width: 350px;">
                                <div class="content">
                                    {% if is_granted('ROLE_PREMIUN') %}

                                    {% else %}
                                        <div class="control">
                                            <button id="submitButton" class="button is-link" disabled>{% trans %}Cpanel.Btn.CreateMenu{% endtrans %}</button>
                                            <a href="{{ path('app_index') }}"><span class="icon is-size-4 is-pulled-right"><ion-icon src="{{asset('images/ico/diamond-outline.svg')}}"></ion-icon></span></a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}